routes/web.php
<?php

Route::get('view_login','LoginController@view_login')->name('view_login');
Route::post('process_login','LoginController@process_login')->name('process_login');

Route::group(['middleware' => 'CheckLogin'],function(){
    Route::resource('schools','SchoolController');
    Route::resource('subjects','SubjectController');

    Route::get('layout','Controller@master');
    Route::get('logout','LoginController@logout');

    Route::get('marks/choose','MarkController@choose');
    Route::post('marks/view','MarkController@view')->name('marks.view');
    Route::post('marks/process','MarkController@process')->name('marks.process');

    Route::get('marks_advanced/choose','MarkController@choose_advanced');
    Route::post('marks_advanced/view','MarkController@view_advanced')->name('marks_advanced.view');
    Route::post('marks_advanced/process','MarkController@process_advanced')->name('marks_advanced.process');
});

app/Models/Subject.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    protected $table = 'subjects';
    protected $fillable = [
        'name',
    ];
//    protected $hidden = ['pivot'];
    public function marks () {
        return $this->belongsToMany( 'App\Models\Student', 'marks' )->using( 'App\Models\MarksAdvanced');
    }
}

app/Http/Controllers/SubjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Subject;
use Illuminate\Http\Request;

class SubjectController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index () {
        $subjects = Subject::get();

        return view( "subjects.index", compact( 'subjects' ) );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create () {
        return view( "subjects.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store ( Request $request ) {
        Subject::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Subject $subject
     *
     * @return \Illuminate\Http\Response
     */
    public function show ( Subject $subject ) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Subject $subject
     *
     * @return \Illuminate\Http\Response
     */
    public function edit ( Subject $subject ) {
        return view( "subjects.edit",compact('subject'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Subject       $subject
     *
     * @return \Illuminate\Http\Response
     */
    public function update ( Request $request, Subject $subject ) {
        $subject->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Subject $subject
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy ( Subject $subject ) {
        $subject->delete();

        return redirect()->route('subjects.index');
    }
}

resources/views/subjects/create.blade.php
<form action="{{ route("subjects.store")}}" method='post'>
    {{ csrf_field() }}
    Name
    <input type="text" name="name">
    <button>Insert</button>
</form>

resources/views/subjects/edit.blade.php
<form action="{{ route("subjects.update",['id' => $subject->id])}}" method='post'>
    {{ method_field('PUT') }}
    {{ csrf_field() }}
    Name
    <input type="text" name="name" value="{{ $subject->name }}">
    <button>Update</button>
</form>

resources/views/subjects/index.blade.php
<a href="{{ route("subjects.create") }}">
    Create
</a>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach ($subjects as $subject)
        <tr>
            <td>
                {{ $subject->id }}
            </td>
            <td>
                {{ $subject->name }}
            </td>
            <td>
                {{ $subject->address }}
            </td>
            <td>
                <a href="{{ route("subjects.edit",['id' => $subject->id]) }}">
                    Edit
                </a>
            </td>
            <td>
                <form action="{{ route("subjects.destroy",['id' => $subject->id]) }}" method="post">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                    <button>Delete</button>
                </form>
            </td>
        </tr>
    @endforeach
</table>