routes/web.php
<?php

Route::get('view_login','LoginController@view_login')->name('view_login');
Route::post('process_login','LoginController@process_login')->name('process_login');

Route::group(['middleware' => 'CheckLogin'],function(){
    Route::resource('schools','SchoolController');
    Route::resource('subjects','SubjectController');

    Route::get('layout','Controller@master');
    Route::get('logout','LoginController@logout');

    Route::get('marks/choose','MarkController@choose');
    Route::post('marks/view','MarkController@view')->name('marks.view');
    Route::post('marks/process','MarkController@process')->name('marks.process');

    Route::get('marks_advanced/choose','MarkController@choose_advanced');
    Route::post('marks_advanced/view','MarkController@view_advanced')->name('marks_advanced.view');
    Route::post('marks_advanced/process','MarkController@process_advanced')->name('marks_advanced.process');
});

app/Models/School.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    protected $table = 'schools';
    protected $fillable = [
        'name',
        'address',
    ];
    public $timestamps = false;

    public function students (  ) {
        return $this->hasMany('App\Models\Student','school_id','id');
    }

}

app/Http/Controllers/SchoolController.php
<?php

namespace App\Http\Controllers;

use App\Models\School;
use Illuminate\Http\Request;

class SchoolController
{
    public $table = 'schools';

    public function index ( Request $request ) {
        $search  = $request->search;
        $schools = School::withCount( 'students' )
            ->where( 'name', 'like', "%$request->search%" )
            ->paginate( 1 );


        return view( "$this->table.index", compact( 'schools', 'search' ) );
    }

    public function create () {
        return view( "$this->table.create" );
    }

    public function store ( Request $request ) {
        School::create( $request->all() );
    }

    public function show ( School $school ) {
        return $school;

        School::updateOrCreate( [
            'ma_sinh_vien' => $request->ma_sinh_vien,
            'ma_mon'       => $request->ma_mon,
        ], [
            'diem' => $request->diem,
        ] );
    }

    public function edit ( School $school ) {
        return view( "$this->table.edit", compact( 'school' ) );
    }

    public function update ( Request $request, School $school ) {
        $school->update( $request->all() );
    }

    public function destroy ( School $school ) {
        $school->delete();

        return redirect()->route( "$this->table.index" );
    }
}

resources/views/schools/create.blade.php
<form action="{{ route("schools.store")}}" method='post'>
    {{ csrf_field() }}
    Name
    <input type="text" name="name">
    <br>
    Address
    <input type="text" name="address">
    <button>Insert</button>
</form>

resources/views/schools/edit.blade.php
<form action="{{ route("schools.update",['id' => $school->id])}}" method='post'>
    {{ method_field('PUT') }}
    {{ csrf_field() }}
    Name
    <input type="text" name="name" value="{{ $school->name }}">
    <br>
    Address
    <input type="text" name="address" value="{{ $school->address }}">
    <button>Update</button>
</form>

resources/views/schools/index.blade.php
@extends('layout.master')

@section('content')
<a href="{{ route("schools.create") }}">
    Create
</a>
<table class="table">
    <caption>
        <form>
            Search
            <input type="search" name="search" value="{{ $search}}">
        </form>
    </caption>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Address</th>
        <th>Number of students</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach ($schools as $school)
        <tr>
            <td>
                {{ $school->id }}
            </td>
            <td>
                {{ $school->name }}
            </td>
            <td>
                {{ $school->address }}
            </td>
            <td>
                {{ $school->students_count }}
            </td>
            <td>
                <a href="{{ route("schools.edit",['id' => $school->id]) }}">
                    Edit
                </a>
            </td>
            <td>
                <form action="{{ route("schools.destroy",['id' => $school->id]) }}" method="post">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                    <button>Delete</button>
                </form>
            </td>
        </tr>
    @endforeach
</table>

{{ $schools->appends(['search' => $search])->links() }}
@endsection